import './globals.css';
import { Inter } from 'next/font/google';
import NavBar from './global/nav-bar/index';
import Footer from './global/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Glassss',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className} suppressHydrationWarning={true}>
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	);
}
